\input texinfo
@setfilename verilog.info
@c $Id$

@ifinfo
@format
INFO-DIR-SECTION Emacs
START-INFO-DIR-ENTRY
* Verilog-mode: (verilog).	The Verilog Mode user guide.
END-INFO-DIR-ENTRY
@end format
@end ifinfo

@ifinfo
This file documents the Verilog-HDL and SystemVerilog editing mode for
XEmacs and FSF Emacs, called the verilog-mode.

Copyright (C) 2016 Free Software Foundation, Inc.
Contributed and written by Michael McNamara and Wilson Snyder. 

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

@ignore
Permission is granted to process this file through Tex and print the
results, provided the printed document carries copying permission notice
identical to this one except for the removal of this paragraph (this
paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy or distribute modified versions of this
manual under the terms of the GPL (for which purpose this text may be
regarded as a program in the language TeX).
@end ifinfo

@setchapternewpage off
@settitle Verilog Mode
@titlepage
@title The Verilog Mode
@subtitle A guide to using the Verilog Mode
@author Michael McNamara
@page

@vskip 0pt plus 1filll
Copyright @copyright{} 2016 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@end titlepage

@node Top
@c Perhaps this should be the title of the document (but only for info,
@c not for TeX).  Existing GNU manuals seem inconsistent on this point.
@top Scope of this Document

This document documents the use and customization of the Verilog-mode
for Emacs.  
@menu
* New Versions::		Getting new versions
* Installing::		        How to install the Verilog Mode
* Getting Started::		Getting started using the Verilog-mode
* Colors::      		Enabling and customizing the colors
* FAQ::			        Frequently Asked Questions
@end menu

@node New Versions
@chapter Getting New Versions

Check the web at @file{http://www.veripool.org/verilog-mode} to see if
there are newer versions of this mode.

@node Installing
@chapter Installing the Verilog-Mode

See http://www.veripool.org/projects/verilog-mode/wiki/Installing
and the instructions at the top of verilog-mode.el.

@node Getting Started
@chapter Getting Started Using the Verilog-Mode

See http://www.veripool.org/projects/verilog-mode/wiki/Documentation
including the papers and presentations therein.

If you visit any Verilog or SystemVerilog file (.v, .vh, .sv, .svh
file extension), in the menu bar there will be a Verilog
item. Underneath this you will find a help item with various subitems.

@node Colors
@chapter Configuring and Using the syntax coloring features

Coloring your code is really cool, impresses your friends, and actually
does help one code quicker, and helps one understand others code. The
only problem is that each version of emacs has different ways of
specifying what color should be used, and hence it is a bear.
      
Select the menu bar @code{Verilog->Customize Verilog Fonts and Colors}
and a nice interface pops up where you can select the font-lock-* faces
to colors that you find pleasing. You can choose the font face, whether
it is bold, italic, and/or underlined; or
all three.
	    
@node FAQ
@chapter Frequently asked questions

See http://www.veripool.org/projects/verilog-mode/wiki/FAQ

@contents
@bye
